### ISSUE TITLE
Populate manga info from tracker

### ISSUE THREAD

**Issue by jeanz3ra** [mihonapp/mihon#138]
### Describe your suggested feature

ability to choose manga cover/artist/state and more from trackers as custom info

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have updated the app to version **[0.16.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment]
I assume you're talking about picking a tracker's (e.g. AniList's) cover image for your library entry in Mihon?
