### ISSUE TITLE
Tracking change causing spam for MangaUpdates API tracking

### ISSUE THREAD

**Issue by cbrumbau** [mihonapp/mihon#17]
### Steps to reproduce

1. Log in with MangaUpdates for tracking
2. Add new entry to be tracked
3. Observe that the score gets assigned -1.0 as opposed to no score as with older tracked entries

### Expected behavior

Scores should be between 0.0 to 10.0, score should show up as no score with new entry as the user hasn't rated it yet

### Actual behavior

Score shows up as -1.0

### Tachiyomi version

0.15.3

### Android version

Android 14

### Device

Google Pixel 7a

### Other details

Haven't migrated to use Mihon yet but haven't noticed any commits that would indicate the issue has been resolved. Looks like the API server is getting hammered so they're banning users to remedy the issue. I've been banned as a user and have logged out of my tracker for now.

[Possibly related to this commit?](https://github.com/mihonapp/mihon/commit/f60782f11fd03b302bb81387f24fd56795f3c6bf)

[MangaUpdates news post about the issue](https://www.mangaupdates.com/news/ug4qow5/tachiyomi-users-please-read-this)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.
